import "@vaadin/button";
import "@vaadin/checkbox";
import "@vaadin/icon";
import "@vaadin/integer-field";
import "@vaadin/select";
import "@vaadin/tabsheet";
import "@vaadin/text-field";
import("@vaadin/confirm-dialog");
import("@vaadin/icons");
import("@vaadin/text-area");
import("./elements");
