import "@vaadin/button";
import "@vaadin/checkbox";
import "@vaadin/confirm-dialog";
import "@vaadin/icon";
import "@vaadin/integer-field";
import "@vaadin/select";
import "@vaadin/tabs";
import "@vaadin/tabs/theme/lumo/vaadin-tabs.js";
import "@vaadin/tabsheet";
import "@vaadin/text-area";
import "@vaadin/text-field";
import("@vaadin/icons");
import("./elements");
