import "@vaadin/button";
import "@vaadin/checkbox";
import "@vaadin/icon";
import("@vaadin/icons");
import "@vaadin/integer-field";
import "@vaadin/select";
import "@vaadin/tabs";
import "@vaadin/tabsheet";
import "@vaadin/text-field";
import "@vaadin/tooltip";
